### PR TITLE
Prefix download URLs with Site frameworks domain

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
@rudigiesler ready for review

**Comment by rudigiesler** [comment]
This looks good to me. Does the Sites framework show up in the Django Admin? I'm just thinking of how we can set the domain name. I think it should either be through django admin, or through a data migration, where it gets the domain name from a setting (which gets its value from an env var).

**Comment by smn** [comment]
It automatically sets it to `domain.com` in a migration that's part of the sites framework and is exposed automatically in the Django admin. It's matter of logging in and changing it there.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
